name: Preview Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  push:
    branches: [main]
    
permissions:
  pull-requests: write
  contents: write

concurrency:
  group: preview-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preview Pages
        uses: rajyan/preview-pages@v1
        with:
          source-dir: .
